// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj92ki2o1W6vk0iZJQyCFQJCbS0SeIYqw',
    appId: '1:621812526980:web:c09d1fb40b3e9f004577d1',
    messagingSenderId: '621812526980',
    projectId: 'fitquest-43cba',
    authDomain: 'fitquest-43cba.firebaseapp.com',
    storageBucket: 'fitquest-43cba.appspot.com',
    measurementId: 'G-10GJL3WBQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4fVNpb_YQ-PO0my7mFRbhnWWgf-a-4vI',
    appId: '1:621812526980:android:9a963cf108d1bb764577d1',
    messagingSenderId: '621812526980',
    projectId: 'fitquest-43cba',
    storageBucket: 'fitquest-43cba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9YYWcQP_uu7X82o_PjjrRtkZ1_Om4kVI',
    appId: '1:621812526980:ios:a8b3177a739badfd4577d1',
    messagingSenderId: '621812526980',
    projectId: 'fitquest-43cba',
    storageBucket: 'fitquest-43cba.appspot.com',
    iosClientId: '621812526980-k5lkpl95kpm1o2l2o3sfq6t63p9sk63j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9YYWcQP_uu7X82o_PjjrRtkZ1_Om4kVI',
    appId: '1:621812526980:ios:a8b3177a739badfd4577d1',
    messagingSenderId: '621812526980',
    projectId: 'fitquest-43cba',
    storageBucket: 'fitquest-43cba.appspot.com',
    iosClientId: '621812526980-k5lkpl95kpm1o2l2o3sfq6t63p9sk63j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitquest',
  );
}
